In [10]:
import pandas as pd
import numpy as np

In [200]:
df=pd.read_csv("../datas/newdf.csv")

In [4]:
df.head()

,Unnamed: 0,Age,Sex,Cholesterol,Heart Rate,Diabetes,Smoking,Obesity,Previous Heart Problems,BMI,systolic,diastolic,Heart Attack Risk
0,0,67,1,208,72,0,1,0,0,31.251233,158,88,0
1,1,21,1,389,98,1,1,1,1,27.194973,165,93,0
2,2,21,0,324,72,1,0,0,1,28.176571,174,99,0
3,3,84,1,383,73,1,1,0,1,36.464704,163,100,0
4,4,66,1,318,93,1,1,1,1,21.809144,91,88,0

In [5]:
y=df.pop('Heart Attack Risk')

In [9]:
df.head()
y

0       0
1       0
2       0
3       0
4       0
       ..
8758    0
8759    0
8760    1
8761    0
8762    1
Name: Heart Attack Risk, Length: 8763, dtype: int64

In [8]:
df.pop('Unnamed: 0')

0          0
1          1
2          2
3          3
4          4
        ...
8758    8758
8759    8759
8760    8760
8761    8761
8762    8762
Name: Unnamed: 0, Length: 8763, dtype: int64

In [14]:
from sklearn.utils.class_weight import compute_class_weight
classwe=compute_class_weight(class_weight='balanced',y=y,classes=np.unique(y))

In [ ]:
classdic={0:classwe[0],1:classwe[1]*}
classdic

{0: 0.7790718349928877, 1: 1.3958266964001274}

In [159]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df,y,test_size=0.20)

In [160]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(class_weight=classdic)

In [161]:
LR.fit(x_train,y_train)

c:\Users\ravik\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight={0: 0.7790718349928877, 1: 2.7916533928002547})

In [129]:
pred=LR.predict(x_test)

In [130]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,pred)

In [134]:
acc

0.6383342840844267

In [132]:
from sklearn.metrics import classification_report,confusion_matrix
clsrep=classification_report(y_test,pred)
conf_mat=confusion_matrix(y_test,pred)

c:\Users\ravik\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ravik\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ravik\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [133]:
print(conf_mat)

[[1119    0]
 [ 634    0]]

In [135]:
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()

In [141]:
h=SS.fit_transform(df)

In [143]:
newdf=pd.DataFrame(h,columns=df.columns)

In [144]:
newdf

,Age,Sex,Cholesterol,Heart Rate,Diabetes,Smoking,Obesity,Previous Heart Problems,BMI,systolic,diastolic
0,0.625557,0.658765,-0.641579,-0.147042,-1.369651,0.339157,-1.002857,-0.991704,0.373454,0.870044,0.193782
1,-1.539322,0.658765,1.596895,1.118179,0.730113,0.339157,0.997151,1.008365,-0.268479,1.135714,0.534480
2,-1.539322,-1.517992,0.793023,-0.147042,0.730113,-2.948488,-1.002857,1.008365,-0.113134,1.477290,0.943319
3,1.425621,0.658765,1.522691,-0.098380,0.730113,0.339157,-1.002857,1.008365,1.198524,1.059809,1.011458
4,0.578495,0.658765,0.718820,0.874867,0.730113,0.339157,0.997151,1.008365,-1.120826,-1.672797,0.193782
...,...,...,...,...,...,...,...,...,...,...,...
8758,0.296119,0.658765,-1.717530,-0.682328,0.730113,0.339157,-1.002857,1.008365,-1.461594,-1.558939,-0.623895
8759,-1.209884,-1.517992,-1.729898,-0.098380,0.730113,-2.948488,0.997151,-0.991704,-0.775078,0.832092,1.147738
8760,-0.315695,0.658765,-0.122154,1.458815,-1.369651,0.339157,0.997151,1.008365,1.030999,0.983903,-0.692035
8761,-0.833383,0.658765,-1.012597,-0.730990,0.730113,0.339157,-1.002857,1.008365,-0.252804,-0.610117,-1.237152
8762,-1.351072,-1.517992,1.188775,-0.001055,0.730113,-2.948488,-1.002857,-0.991704,0.636623,0.110987,-1.237152

In [140]:
SS

StandardScaler()

In [183]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(newdf,y,test_size=0.20)
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(class_weight=classdic)
LR.fit(x_train,y_train)
pred=LR.predict(x_test)

In [184]:
pred=LR.predict(x_test)
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,pred)

In [185]:
acc

0.4934398174557901

In [186]:
y_test

1554    0
5828    0
3664    0
5063    1
7336    1
       ..
7137    0
8499    1
4268    0
871     1
191     1
Name: Heart Attack Risk, Length: 1753, dtype: int64

In [187]:
x_test

,Age,Sex,Cholesterol,Heart Rate,Diabetes,Smoking,Obesity,Previous Heart Problems,BMI,systolic,diastolic
1554,1.378559,-1.517992,-0.876557,0.193594,0.730113,0.339157,-1.002857,-0.991704,1.163485,0.224846,-1.373432
5828,-0.551008,0.658765,0.768289,0.534231,-1.369651,0.339157,0.997151,1.008365,-0.988323,-0.230589,0.602620
3664,-0.268632,0.658765,-0.357132,0.680218,0.730113,0.339157,0.997151,-0.991704,-0.863938,0.300751,1.692856
5063,0.907933,-1.517992,1.535059,-1.412263,-1.369651,0.339157,0.997151,-0.991704,-0.174236,0.262799,-1.305292
7336,-0.033319,0.658765,-1.630960,-1.120289,0.730113,0.339157,0.997151,1.008365,0.135115,-0.382400,-1.373432
...,...,...,...,...,...,...,...,...,...,...,...
7137,-0.833383,0.658765,1.646364,-1.363600,-1.369651,0.339157,-1.002857,-0.991704,-0.013432,1.211620,-0.692035
8499,0.907933,0.658765,0.323067,-1.266276,-1.369651,0.339157,-1.002857,1.008365,-0.633501,-1.520986,-0.078777
4268,1.002058,0.658765,1.188775,-1.266276,0.730113,0.339157,-1.002857,-0.991704,1.102062,-0.078777,0.261922
871,-0.268632,0.658765,-0.023216,1.361490,0.730113,0.339157,-1.002857,-0.991704,-0.747739,1.629102,1.352157
191,0.296119,-1.517992,1.448488,-1.266276,-1.369651,0.339157,-1.002857,-0.991704,-0.576153,-0.382400,0.670760

In [188]:
confusion_matrix(y_test,pred)

array([[554, 579],
       [309, 311]], dtype=int64)

In [189]:
classdic={0:classwe[0],1:classwe[1]}
classdic

{0: 0.7790718349928877, 1: 1.3958266964001274}

In [193]:
h=np.array(y).reshape(-1,1)

In [197]:
Y=SS.fit_transform(h)

In [198]:
Y

array([[-0.74709014],
       [-0.74709014],
       [-0.74709014],
       ...,
       [ 1.33852658],
       [-0.74709014],
       [ 1.33852658]])

In [210]:
df[df['Heart Attack Risk']==0].count()

Unnamed: 0                 5624
Age                        5624
Sex                        5624
Cholesterol                5624
Heart Rate                 5624
Diabetes                   5624
Smoking                    5624
Obesity                    5624
Previous Heart Problems    5624
BMI                        5624
systolic                   5624
diastolic                  5624
Heart Attack Risk          5624
dtype: int64

In [211]:
from xgboost import XGBClassifier

xgb = XGBClassifier(scale_pos_weight=len(y_train[y_train==0]) / len(y_train[y_train==1]))
xgb.fit(x_train, y_train)
pred = xgb.predict(x_test)

ModuleNotFoundError: No module named 'xgboost'